### ISSUE TITLE
dkms error due to non-existent source after driver updates

### ISSUE THREAD

**Issue by adatum** [negativo17/dkms-nvidia#12] opened 2019-06-17 08:41 UTC
After nvidia driver updates (eg. from 430.14 to 430.26), `dkms status` and `dkms autoinstall` show:

    Error! Could not locate dkms.conf file.
    File: /var/lib/dkms/nvidia/430.14/source/dkms.conf does not exist.

`/var/lib/dkms/nvidia/430.14/source` is a broken link to `/usr/src/nvidia-430.14` which no longer exists after the update.

I have to manually delete `/var/lib/dkms/nvidia/430.14/` and run `dkms autoinstall`. 

Is there a way to avoid this intervention?

**Comment by scaronni** [comment] 2019-06-17 09:55
Did you upgrade the `dkms-nvidia` package along with the kernel in the same `dnf/yum` transaction?

**Comment by adatum** [comment] 2019-06-17 10:03
Yes. Here is the latest `dnf history`. Also, this issue not new, as it has been present since I started using the nvidia drivers from negativo17 more than a year ago.

```
Packages Altered:
    Upgrade  dkms-nvidia-3:430.26-1.fc30.x86_64             @fedora-nvidia
    Upgraded dkms-nvidia-3:430.14-1.fc30.x86_64             @@System
    Upgrade  nvidia-driver-3:430.26-1.fc30.x86_64           @fedora-nvidia
    Upgraded nvidia-driver-3:430.14-1.fc30.x86_64           @@System
    Upgrade  nvidia-driver-NVML-3:430.26-1.fc30.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-NVML-3:430.14-1.fc30.x86_64      @@System
    Upgrade  nvidia-driver-cuda-3:430.26-1.fc30.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-cuda-3:430.14-1.fc30.x86_64      @@System
    Upgrade  nvidia-driver-cuda-libs-3:430.26-1.fc30.x86_64 @fedora-nvidia
    Upgraded nvidia-driver-cuda-libs-3:430.14-1.fc30.x86_64 @@System
    Upgrade  nvidia-driver-libs-3:430.26-1.fc30.i686        @fedora-nvidia
    Upgraded nvidia-driver-libs-3:430.14-1.fc30.i686        @@System
    Upgrade  nvidia-driver-libs-3:430.26-1.fc30.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-libs-3:430.14-1.fc30.x86_64      @@System
    Upgrade  nvidia-kmod-common-3:430.26-1.fc30.noarch      @fedora-nvidia
    Upgraded nvidia-kmod-common-3:430.14-1.fc30.noarch      @@System
    Upgrade  nvidia-libXNVCtrl-3:430.26-2.fc30.x86_64       @fedora-nvidia
    Upgraded nvidia-libXNVCtrl-3:430.14-1.fc30.x86_64       @@System
    Upgrade  nvidia-persistenced-3:430.26-1.fc30.x86_64     @fedora-nvidia
    Upgraded nvidia-persistenced-3:430.14-1.fc30.x86_64     @@System
    Upgrade  nvidia-settings-3:430.26-2.fc30.x86_64         @fedora-nvidia
    Upgraded nvidia-settings-3:430.14-1.fc30.x86_64         @@System
Scriptlet output:
   1 /sbin/ldconfig: /lib64/libXNVCtrl.so.0 is not a symbolic link

```

**Comment by adatum** [comment] 2019-12-16 03:51
The issue still persists. Upon upgrading to 440.40:

> Error! Could not locate dkms.conf file.
> File: /var/lib/dkms/nvidia/440.36/source/dkms.conf does not exist.

The workaround is simple, but it would be nice to solve this. 

Let me know if I can help in some way.

**Comment by scaronni** [comment] 2019-12-18 14:23
Hello, the issue is not related to the drivers packaged here, it's inside DKSM. It happens only when you have a kernel upgrade and a DKMS package update in the same yum/dnf transaction.

Whenever this case, you have that error. It would be nice if you could investigate in DKMS and open a Pull Request there, unfortunately I don't have time. I can help you though in getting it merged:

https://github.com/dell/dkms

**Comment by adatum** [comment] 2019-12-18 15:28
The issue happened when upgrading only nvidia drivers, and nothing else (no kernel upgrade).

This is the complete `dnf history info` of the transaction: 
```
Packages Altered:
    Upgrade  dkms-nvidia-3:440.44-1.fc31.x86_64             @fedora-nvidia
    Upgraded dkms-nvidia-3:440.36-1.fc31.x86_64             @@System
    Upgrade  nvidia-driver-3:440.44-1.fc31.x86_64           @fedora-nvidia
    Upgraded nvidia-driver-3:440.36-1.fc31.x86_64           @@System
    Upgrade  nvidia-driver-NVML-3:440.44-1.fc31.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-NVML-3:440.36-1.fc31.x86_64      @@System
    Upgrade  nvidia-driver-cuda-3:440.44-1.fc31.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-cuda-3:440.36-1.fc31.x86_64      @@System
    Upgrade  nvidia-driver-cuda-libs-3:440.44-1.fc31.x86_64 @fedora-nvidia
    Upgraded nvidia-driver-cuda-libs-3:440.36-1.fc31.x86_64 @@System
    Upgrade  nvidia-driver-libs-3:440.44-1.fc31.i686        @fedora-nvidia
    Upgraded nvidia-driver-libs-3:440.36-1.fc31.i686        @@System
    Upgrade  nvidia-driver-libs-3:440.44-1.fc31.x86_64      @fedora-nvidia
    Upgraded nvidia-driver-libs-3:440.36-1.fc31.x86_64      @@System
    Upgrade  nvidia-kmod-common-3:440.44-1.fc31.noarch      @fedora-nvidia
    Upgraded nvidia-kmod-common-3:440.36-1.fc31.noarch      @@System
    Upgrade  nvidia-libXNVCtrl-3:440.44-1.fc31.x86_64       @fedora-nvidia
    Upgraded nvidia-libXNVCtrl-3:440.36-1.fc31.x86_64       @@System
    Upgrade  nvidia-persistenced-3:440.44-1.fc31.x86_64     @fedora-nvidia
    Upgraded nvidia-persistenced-3:440.36-1.fc31.x86_64     @@System
    Upgrade  nvidia-settings-3:440.44-1.fc31.x86_64         @fedora-nvidia
    Upgraded nvidia-settings-3:440.36-1.fc31.x86_64         @@System

```

**Comment by scaronni** [comment] 2019-12-18 15:43
Never happened to me in this condition. Do you have by chance a new kernel pending for reboot? So `kernel-devel` is already updated in the system?

**Comment by adatum** [comment] 2019-12-18 15:52
No, I don't think I had a new kernel pending for reboot.

**Comment by scr4bble** [comment] 2020-04-04 21:47
Same or similar issue here:
Just updated F30 system and got the same errors from scriptlet:
Installed package `kmod-nvidia` `kmod-bbswitch` and kernel in the same dnf transaction.

Error! Could not locate dkms.conf file.
File: /var/lib/dkms/nvidia/430.40/source/dkms.conf does not exist.

Broken symlink from `/var/lib/dkms/nvidia/430.40/source -> /usr/src/nvidia-430.40`
Now I fixed it to point to the new version `ln -s /usr/src/nvidia-440.64 source`

Dkms still have the information about the old nvidia version though - is it a problem? I tried to reinstall dkms-nvidia kmod-nvidia kmod-bbswitch but no difference.
```
# dkms status
nvidia, 430.40: added
```

**Comment by scr4bble** [comment] 2020-04-04 22:06
So now it's
```
# dkms status
nvidia, 430.40, 5.5.10-100.fc30.x86_64, x86_64: installed (original_module exists) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!)
```

**Comment by scr4bble** [comment] 2020-04-04 22:16
```
# Now old module removed
dkms remove nvidia/430.40 --all

# and new one installed
dkms install -m nvidia -v 440.64

# status now
$ dkms status
nvidia, 430.40: added
nvidia, 440.64, 5.5.10-100.fc30.x86_64, x86_64: installed (original_module exists) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!)
```

Then I ran `dkms remove nvidia/430.40 --all` again
```
# dkms status
nvidia, 430.40: added
nvidia, 440.64, 5.5.10-100.fc30.x86_64, x86_64: built

```

**Comment by adatum** [comment] 2020-05-04 19:45
After upgrading from F31 to F32, the nvidia kernel modules were not installed, and `/var/lib/dkms/nvidia` did not even exist. 

I tried reinstalling `dkms-nvidia` while watching the `/var/lib/dkms` directory. The `nvidia` directory was creating in the middle of the reinstallation, but at some point disappeared, and an SELinux error was reported:  

> avc:  denied  { open } for  pid=9681 comm="systemd-modules" path="/sys/firmware/efi/efivars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c" dev="efivarfs" ino=19532 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:efivarfs_t:s0 tclass=file permissive=0

I had previously encountered a similar situation with the dkms modules vanishing in F31, and I don't remember how I fixed it, though it was probably by manually using `dkms install` as detailed above. In this case, I'm guessing the SELinux issues have to do with Fedora and not negativo17.

In any case, I uninstalled `dkms-nvidia` and installed `akmod-nvidia` instead, and so far I have no more problems.

**Comment by scaronni** [comment] 2020-05-09 06:16
There is still a bug in DKMS that gets triggered when both a new kernel and `dkms` driver packages get installed at the same time (for example in the case of the above upgrade). The but should be fixed in DKMS directly.

**Comment by adatum** [comment] 2020-05-09 06:19
> There is still a bug in DKMS that gets triggered when both a new kernel and dkms driver packages get installed at the same time

Would the DKMS bug prevent `dkms-nvidia` from reinstalling properly after having rebooted into the new kernel?

**Comment by scaronni** [comment] 2020-05-09 07:42
It actually happens during the transaction, doesn't matter if you reboot or not. Kernel + new dkms package can not be in the same dnf transaction.

**Comment by adatum** [comment] 2020-05-09 07:51
The `dkms-nvidia` reinstallation was not in the same dnf transaction and it failed. Technically it succeeded, but the `nvidia` directory appeared and then vanished from `/var/lib/dkms`.

**Comment by brittyazel** [comment] 2024-10-16 06:36
> The `dkms-nvidia` reinstallation was not in the same dnf transaction and it failed. Technically it succeeded, but the `nvidia` directory appeared and then vanished from `/var/lib/dkms`.

I believe I'm seeing this issue as well. Every time I run "sudo dnf reinstall dkms-nvidia" I end up with zero working dkms modules installed as verified by "sudo dkms status". I have to manually build and install the dkms modules again to get them back. This is 100% repeatable.

**Comment by scaronni** [comment] 2024-10-16 14:05
I'll have a look.

**Comment by scaronni** [comment] 2024-10-16 15:00
Ok, I think I figured this out, it's fully reproducible by removing hiding the output (`-q`) in the SPEC file and do a few reinstallations.

Without the `--rpm_safe_upgrade` switch, the `%preun` section of the package being reinstalled is executed after the installation of the new one, removing everything. This of course, happen only when the DKMS version is the same, never on an upgrade which involves a change of version.

In more than 10 years of packaging this, I can't believe I've never hit this. Well, better late than never.

I'm updating all the DKMS spec files that I have in my repository to fix this. Btw, the issue when installing a new kernel along with an updated DKMS package does no longer happen, so it seems this was the only issue left.

**Comment by brittyazel** [comment] 2024-10-16 15:18
Thank you so very much for looking into this. I was pulling my hair out last night 😋

**Comment by scaronni** [comment] 2024-10-16 15:22
- https://github.com/negativo17/dkms-xpadneo/commit/e4dd70307ca24bb97a01a8e70ad9a406f9fdbf39
- https://github.com/negativo17/dkms-xone/commit/f2f1c208b67a0a829118a8f9d4745523ff1ae380
- https://github.com/negativo17/dkms-nullfs/commit/a9124eb3b13dba90c82e7810a1da7e7a59b9fbce
- https://github.com/negativo17/dkms-evdi/commit/c198be30304bbc3e4f07e2fac6d350132c5e0a6d
- https://github.com/negativo17/dkms-nvidia/commit/359c86a3cd9e48f83ca6086a9e5b205d2cf88a99

Btw, I'm also the maintainer of DKMS, so double failure :rofl: 

Packages will be online shortly.

**Closed as completed by scaronni** 2024-10-16 15:22 UTC

**Comment by scaronni** [comment] 2024-10-16 15:23
I'll make sure that the fix will be in any new DKMS/rpms released in the future by Nvidia for the CUDA repository.

**Comment by scaronni** [comment] 2024-10-16 15:29
Please note that even with the updated package, you will hit this **at least one more time**, as the `%preun` scriptlet that is executed is the one of the installed package that is being replaced, not the one being installed. It will be ok at the second reinstallation or at the first upgrade, whichever comes first on your system.

**Comment by brittyazel** [comment] 2024-10-16 15:32
Understood. Will running "sudo dnf reinstall dkms-nvidia" twice back-to-back be adequate to get it back to a working state?

**Comment by scaronni** [comment] 2024-10-16 15:37
It's already a working state as of now if you don't reinstall the same module without changing version. Otherwise yes, it's two times. First update that is coming will still execute the `%preun` from the old package, then reinstalling fixes it by readding the DKMS module and leaving in place a `%preun` scriptlet that will not trigger the next time.
